### ISSUE TITLE
Add ability to send haptic commands to another computer.

### ISSUE THREAD

**Issue by LunarTiger** [intiface/intiface-game-haptics-router#19]
Adding an option to not use the embedded intiface software but to instead connect to an intiface server running on another computer. So, for example, a computer on address 10.0.0.2 would run the GHR and pipe the commands through to a computer on 10.0.0.3 that is just be running the intiface server and has whatever toy connected.

**Comment by qdot** [comment]
Closing this, but that doesn't mean it's not getting fixed. Rather, Intiface Desktop should handle this bouncing rather than the GHR, as the GHR should do the minimal amount possible with Buttplug. This is still going to take a while, but it's definitely on my todo list.
