### ISSUE TITLE
Can't attach/route to games loaded through Xbox app

### ISSUE THREAD

**Issue by iznaut** [intiface/intiface-game-haptics-router#25]
I tried a handful of games through Xbox Game Pass with little success. Some would not show up in the process list at all (may just be specific to those games) but the ones that I was able to attach to didn't route any vibrations.

I used Enter the Gungeon as a test case since I have it on Steam as well - the Steam version will attach and route vibrations without issue, while the Game Pass version will not route vibrations after attaching.

**Comment by qdot** [comment]
I'm gonna guess the XBox app uses the newer UWP stuff, which we don't hook yet. I'll have to see if that's even possible.

**Comment by qdot** [comment]
It took 3 years, but we're now using UWP, which... I hope should fix this but I also don't have a game pass account at the moment so I can't check.
