### ISSUE TITLE
Dust: An Elysian Tail doesn't work with GHR

### ISSUE THREAD

**Issue by qdot** [intiface/intiface-game-haptics-router#26]
GHR can attach to process, but no vibration is routed.

**Comment by franckroad** [comment]
Hello,

I am the user who you have speaked on discord. You have created this issue for me. Have you work on this problem.

Thank you for your help.

**Comment by qdot** [comment]
@franckroad Well, 3 years later, I just tested Dust again and it works fine with the current version of the GHR. Closing this and adding the game to our compatibility list.
