### ISSUE TITLE
Gamepad Connection issue in V11

### ISSUE THREAD

**Issue by iFeelPixel** [intiface/intiface-game-haptics-router#30]
Hi, I have tested v10 and v11. v10 is fully functional but v11 has a device connection issue. Gaming controllers (XBox one, Logitech F710) are not correctly listed. Logs report there is a problem with the bluetooth stack. Xinput vizualizer is working but rumble does not pass trough gamepad. Known issue?

**Comment by qdot** [comment]
Oh, yeah, that was an issue with the version of buttplug-rs that v11 is built on. I just need to bring it up to the latest version, which will happen in the next day or two.

**Comment by iFeelPixel** [comment]
Thanks. Good to know that it will be easy fixed. Keep the great work! Looking forward for some versions with Gaming mouse (Rival 500/700) and PS5 controllers (Dual Sense) support.

**Comment by qdot** [comment]
This should be fixed, but you'll need to download the latest version manually because I broke the updater too (now fixed in v13).
