### ISSUE TITLE
Allow GHR to reroute secondary controller to support Rez Infinite

### ISSUE THREAD

**Issue by april** [intiface/intiface-game-haptics-router#39]
Currently GHR reroutes the haptics from the primary controller, which works great for 99% of games.

However, this doesn't work for Rez Infinite, which has two vibration control settings:

- Vibration (which vibrates for things like weapon firing and level transitions, aka super boring stuff)
- Trance Vibration (which vibrates to the music, aka the Good Shit™)

Vibration is sent to the primary controller (aka controller 0) and Trance Vibration is sent to all the other controllers (aka controller 1-5 or whatever). As a result, it's impossible to get the fun Trance Vibration from Rez Infinite with GHR.

It would be great if GHR could get an update to support rerouting the haptics from the secondary controller(s).

In theory you could do a bunch of really complicated stuff and support arbitrary mappings of any number of XInput devices to output devices, but even a simple checkmark that changes GHR from routing controller 0 (primary) to routing controller 1 (secondary) would make Trance Vibration work and probably handle any other game that wanted to do something like this.

Thanks, and happy to beta test this for you.

**Comment by qdot** [comment]
This now exists in a very crude way in v17. I'll be adding extra UI to map controller to toy in v18, so you can have multiple toys mapped to different controllers. Making this as done and creating a new issue for that.

**Comment by april** [comment]
Thanks for this, can’t wait to check it out!
